<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'FRoemer\\Tmmarket\\' => array($typo3InstallDir . 'typo3conf/ext/tmmarket/Classes'),
    'Netresearch\\RteCKEditorImage\\' => array($typo3InstallDir . 'typo3conf/ext/t3x-rte_ckeditor_image/Classes'),
    'PhpParser\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Resources/Private/PHP/PHP-Parser/lib/PhpParser'),
);
