<?php
return [
    'BE' => [
        'debug' => false,
        'explicitADmode' => 'explicitAllow',
        'installToolPassword' => '$pbkdf2-sha256$25000$OqyVvoTzgts9q59JUm033A$jZQ8rNrUgMcmXQvW1cPENasUKolO4510s.bPi7ClfpU',
        'loginSecurityLevel' => 'rsa',
    ],
    'DB' => [
        'Connections' => [
            'Default' => [
                'charset' => 'utf8',
                'dbname' => 'tmmarket',
                'driver' => 'mysqli',
                'host' => '127.0.0.1',
                'password' => 'oeconomicus1',
                'port' => 3306,
                'user' => 'root',
            ],
        ],
    ],
    'EXT' => [
        'extConf' => [
            'browser' => 'a:8:{s:8:"LLstatic";s:7:"English";s:17:"external_links_02";s:1:"0";s:8:"drs_mode";s:18:"Don\'t log anything";s:28:"drs_pageNotFoundOnCHashError";s:1:"1";s:27:"drs_cHashExcludedParameters";s:1:"1";s:17:"external_links_03";s:1:"0";s:15:"showSampleTasks";s:1:"0";s:17:"external_links_04";s:1:"0";}',
            'caddy' => 'a:19:{s:21:"evaluatorTYPO3version";s:35:"Undefined error: Evaluation failed!";s:22:"evaluatorExternalLinks";s:1:"1";s:17:"evaluatorSponsors";s:1:"1";s:16:"databaseReadonly";s:1:"1";s:21:"databaseExternalLinks";s:1:"1";s:16:"databaseSponsors";s:1:"1";s:12:"debuggingDrs";s:8:"Disabled";s:16:"debuggingConsole";s:8:"Disabled";s:22:"debuggingExternalLinks";s:1:"1";s:17:"debuggingSponsors";s:1:"1";s:14:"labellingCaddy";s:15:"Caddy (default)";s:13:"labellingItem";s:14:"Item (default)";s:29:"labellingPaymentCashInAdvance";s:25:"Cash in advance (default)";s:10:"beLanguage";s:7:"English";s:23:"beLanguageExternalLinks";s:1:"1";s:18:"beLanguageSponsors";s:1:"1";s:16:"watchlistEnabled";s:1:"0";s:22:"watchlistExternalLinks";s:1:"1";s:17:"watchlistSponsors";s:1:"1";}',
            'css_styled_content' => 'a:0:{}',
            'direct_mail' => 'a:9:{s:12:"sendPerCycle";s:2:"50";s:13:"cron_language";s:2:"en";s:14:"addRecipFields";s:0:"";s:10:"adminEmail";s:17:"admin@website.com";s:7:"cronInt";s:1:"5";s:15:"notificationJob";s:1:"1";s:19:"enablePlainTextNews";s:1:"1";s:14:"UseHttpToFetch";s:1:"0";s:13:"updateMessage";s:1:"0";}',
            'div2007' => 'a:0:{}',
            'doc_tt_products' => 'a:0:{}',
            'dynaflex' => 'a:0:{}',
            'extension_builder' => 'a:3:{s:15:"enableRoundtrip";s:1:"1";s:15:"backupExtension";s:1:"1";s:9:"backupDir";s:35:"uploads/tx_extensionbuilder/backups";}',
            'gridelements' => 'a:3:{s:20:"additionalStylesheet";s:0:"";s:19:"nestingInListModule";s:1:"0";s:26:"overlayShortcutTranslation";s:1:"0";}',
            'indexed_search' => 'a:19:{s:8:"pdftools";s:9:"/usr/bin/";s:8:"pdf_mode";s:2:"20";s:5:"unzip";s:9:"/usr/bin/";s:6:"catdoc";s:9:"/usr/bin/";s:6:"xlhtml";s:9:"/usr/bin/";s:7:"ppthtml";s:9:"/usr/bin/";s:5:"unrtf";s:9:"/usr/bin/";s:9:"debugMode";s:1:"0";s:18:"fullTextDataLength";s:1:"0";s:23:"disableFrontendIndexing";s:1:"0";s:21:"enableMetaphoneSearch";s:1:"1";s:6:"minAge";s:2:"24";s:6:"maxAge";s:1:"0";s:16:"maxExternalFiles";s:1:"5";s:26:"useCrawlerForExternalFiles";s:1:"0";s:11:"flagBitMask";s:3:"192";s:16:"ignoreExtensions";s:0:"";s:17:"indexExternalURLs";s:1:"0";s:16:"useMysqlFulltext";s:1:"0";}',
            'jumpurl' => 'a:0:{}',
            'launch' => 'a:0:{}',
            'launchquickshop' => 'a:0:{}',
            'leaflet' => 'a:0:{}',
            'migration_core' => 'a:0:{}',
            'powermail' => 'a:8:{s:12:"disableIpLog";s:1:"1";s:27:"disableMarketingInformation";s:1:"0";s:20:"disableBackendModule";s:1:"0";s:24:"disablePluginInformation";s:1:"0";s:35:"disablePluginInformationMailPreview";s:1:"0";s:13:"enableCaching";s:1:"0";s:15:"l10n_mode_merge";s:1:"0";s:29:"replaceIrreWithElementBrowser";s:1:"0";}',
            'quick_shop' => 'a:21:{s:6:"update";s:1:"0";s:19:"updateExternalLinks";s:1:"0";s:20:"backendstyleDisabled";s:1:"0";s:17:"backendstyleHosts";s:0:"";s:25:"backendstyleExternalLinks";s:1:"0";s:4:"fal.";a:2:{s:8:"disabled";s:1:"0";s:13:"externalLinks";s:1:"0";}s:10:"geocoding.";a:2:{s:7:"enabled";s:1:"0";s:13:"externalLinks";s:1:"0";}s:13:"labellingItem";s:14:"Item (default)";s:21:"labellingItemCategory";s:18:"Category (default)";s:22:"labellingItemDimension";s:19:"Dimension (default)";s:18:"labellingItemGroup";s:15:"Group (default)";s:21:"labellingItemMaterial";s:18:"Material (default)";s:17:"labellingProvider";s:18:"Provider (default)";s:25:"labellingProviderCategory";s:18:"Category (default)";s:22:"labellingExternalLinks";s:1:"0";s:12:"linkhandler.";a:5:{s:21:"tx_quickshop_products";s:17:"Yes (recommended)";s:22:"tx_quickshop_products.";a:1:{s:8:"onlyPids";s:0:"";}s:21:"tx_quickshop_provider";s:17:"Yes (recommended)";s:22:"tx_quickshop_provider.";a:1:{s:8:"onlyPids";s:0:"";}s:13:"ExternalLinks";s:1:"0";}s:9:"LLsupport";s:28:"No. I use one language only.";s:22:"LLsupportExternalLinks";s:1:"0";s:18:"tcaProductOrdering";s:1:"0";s:25:"tcaRecordsOnStandardPages";s:1:"0";s:16:"tcaExternalLinks";s:1:"0";}',
            'radialsearch' => 'a:6:{s:13:"versionPrompt";s:1:"0";s:8:"LLstatic";s:7:"English";s:18:"external_linksBase";s:1:"0";s:9:"database.";a:6:{s:3:"pid";s:1:"0";s:4:"info";s:52:"ERROR: tx_radialsearch_em->databaseInfo doesn\'t work";s:4:"path";s:56:"typo3conf/ext/radialsearch/Resources/Private/Postalcodes";s:8:"truncate";s:1:"0";s:9:"selectbox";s:0:"";s:13:"externalLinks";s:1:"0";}s:4:"drs.";a:2:{s:7:"enabled";s:8:"Disabled";s:13:"externalLinks";s:1:"0";}s:6:"earth.";a:2:{s:7:"radius.";a:2:{s:2:"km";s:6:"6378.2";s:5:"miles";s:6:"3963.2";}s:13:"externalLinks";s:1:"0";}}',
            'realurl' => 'a:6:{s:10:"configFile";s:26:"typo3conf/realurl_conf.php";s:14:"enableAutoConf";s:1:"1";s:14:"autoConfFormat";s:1:"0";s:17:"segTitleFieldList";s:0:"";s:12:"enableDevLog";s:1:"0";s:10:"moduleIcon";s:1:"0";}',
            'recycler' => 'a:0:{}',
            'refresh' => 'a:4:{s:22:"databaseConnectionMode";s:20:"$GLOBALS[ TYPO3_DB ]";s:31:"databaseConnectionExternalLinks";s:1:"0";s:13:"debuggingMode";s:8:"Disabled";s:21:"debuggingExternalLnks";s:1:"0";}',
            'rsaauth' => 'a:1:{s:18:"temporaryDirectory";s:0:"";}',
            'saltedpasswords' => 'a:2:{s:3:"BE.";a:4:{s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\Pbkdf2Salt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}s:3:"FE.";a:5:{s:7:"enabled";i:1;s:21:"saltedPWHashingMethod";s:41:"TYPO3\\CMS\\Saltedpasswords\\Salt\\Pbkdf2Salt";s:11:"forceSalted";i:0;s:15:"onlyAuthService";i:0;s:12:"updatePasswd";i:1;}}',
            'scheduler' => 'a:4:{s:11:"maxLifetime";s:4:"1440";s:11:"enableBELog";s:1:"1";s:15:"showSampleTasks";s:1:"1";s:11:"useAtdaemon";s:1:"0";}',
            'seo_dynamic_tag' => 'a:0:{}',
            'slick' => 'a:0:{}',
            'start' => 'a:9:{s:22:"backendLayoutsDisabled";s:1:"0";s:20:"backendstyleDisabled";s:1:"0";s:17:"backendstyleHosts";s:0:"";s:10:"beLanguage";s:7:"English";s:16:"tcaPagesDisabled";s:1:"0";s:20:"tcaTtcontentDisabled";s:1:"0";s:18:"tcaBeusersDisabled";s:1:"0";s:19:"tcaBegroupsDisabled";s:1:"0";s:24:"tcaSysfilemountsDisabled";s:1:"0";}',
            'startcustomer' => 'a:0:{}',
            'startfeuser' => 'a:0:{}',
            'static_info_tables' => 'a:1:{s:13:"enableManager";s:1:"0";}',
            't3_tcpdf' => 'a:0:{}',
            't3foundation' => 'a:2:{s:6:"useRTE";s:1:"0";s:9:"addPanels";s:1:"0";}',
            't3x-rte_ckeditor_image' => 'a:0:{}',
            'table' => 'a:0:{}',
            'tmmarket' => 'a:0:{}',
            'tsconf' => 'a:14:{s:22:"page_tceform_ttcontent";s:1:"1";s:19:"tca_ttcontentimages";s:21:"Default (recommended)";s:27:"page_mod_shared_deflangauge";s:0:"";s:15:"tca_systemplate";s:1:"1";s:35:"user_options_filelist_enableButtons";s:1:"1";s:33:"page_mod_web_layout_menu_function";s:1:"0";s:31:"page_mod_web_list_enableButtons";s:1:"1";s:9:"mytsconf.";a:1:{s:4:"path";s:58:"typo3conf/ext/tsconf/Resources/Private/myPageTreeIcons.php";}s:24:"user_options_pagetreeuid";s:1:"1";s:30:"pagetree_enhanced_context_menu";s:1:"1";s:15:"user_adminpanel";s:1:"1";s:18:"user_options_cache";s:1:"1";s:21:"user_clearcachesystem";s:1:"1";s:32:"user_options_defaultUploadFolder";s:1:"0";}',
            'tsparser' => 'a:0:{}',
            'tt_address' => 'a:3:{s:21:"backwardsCompatFormat";s:9:"%1$s %3$s";s:24:"storeBackwardsCompatName";s:1:"1";s:17:"readOnlyNameField";s:1:"1";}',
            'tt_products' => 'a:13:{s:14:"pageAsCategory";s:1:"0";s:12:"useFlexforms";s:1:"1";s:12:"addressTable";s:0:"";s:11:"imageFolder";s:12:"uploads/pics";s:20:"orderBySortingTables";s:0:"";s:11:"articleMode";s:1:"0";s:12:"templateFile";s:54:"EXT:tt_products/template/example_template_bill_de.tmpl";s:13:"templateCheck";s:35:"/([^#]+(#{2}|#{5}|#{7,8})([^#])+?)/";s:11:"endtimeYear";s:4:"2027";s:6:"where.";a:1:{s:8:"category";s:0:"";}s:5:"hook.";a:1:{s:12:"setPageTitle";s:1:"1";}s:8:"exclude.";a:8:{s:11:"tt_products";s:0:"";s:20:"tt_products_language";s:19:"datasheet,www,image";s:15:"tt_products_cat";s:0:"";s:20:"tt_products_articles";s:0:"";s:29:"tt_products_articles_language";s:0:"";s:17:"tt_products_texts";s:0:"";s:26:"tt_products_texts_language";s:0:"";s:19:"sys_products_orders";s:51:"client_ip,date_of_birth,telephone,fax,ac_uid,cc_uid";}s:6:"cache.";a:2:{s:7:"backend";s:1:"0";s:8:"options.";a:1:{s:7:"servers";s:0:"";}}}',
        ],
    ],
    'EXTCONF' => [
        'lang' => [
            'availableLanguages' => [
                'fr',
                'de',
                'es',
            ],
        ],
    ],
    'FE' => [
        'debug' => false,
        'loginSecurityLevel' => 'rsa',
    ],
    'GFX' => [
        'jpg_quality' => '80',
        'processor' => 'ImageMagick',
        'processor_allowTemporaryMasksAsPng' => false,
        'processor_colorspace' => 'sRGB',
        'processor_effects' => 1,
        'processor_enabled' => true,
        'processor_path' => 'C:/xampp/ImageMagick/',
        'processor_path_lzw' => 'C:/xampp/ImageMagick/',
    ],
    'MAIL' => [
        'transport' => 'sendmail',
        'transport_sendmail_command' => 'C:\\xampp\\mailtodisk\\mailtodisk.exe',
        'transport_smtp_encrypt' => '',
        'transport_smtp_password' => '',
        'transport_smtp_server' => '',
        'transport_smtp_username' => '',
    ],
    'SYS' => [
        'caching' => [
            'cacheConfigurations' => [
                'extbase_object' => [
                    'backend' => 'TYPO3\\CMS\\Core\\Cache\\Backend\\Typo3DatabaseBackend',
                    'frontend' => 'TYPO3\\CMS\\Core\\Cache\\Frontend\\VariableFrontend',
                    'groups' => [
                        'system',
                    ],
                    'options' => [
                        'defaultLifetime' => 0,
                    ],
                ],
            ],
        ],
        'devIPmask' => '',
        'displayErrors' => 1,
        'enableDeprecationLog' => false,
        'encryptionKey' => '1de3798a56f27a2dc03b28eaea4a81249ddf582b2b548d3b83ee6ccedf57de9b9aa4d080efdaeb2b40997fe63a775323',
        'exceptionalErrors' => 20480,
        'isInitialDatabaseImportDone' => true,
        'isInitialInstallationInProgress' => false,
        'sitename' => 'Cange Supermarket',
        'sqlDebug' => 1,
        'systemLogLevel' => 2,
    ],
];
